server:
   port: ${PORT:5000}

security:
  user:
    name: root
    password: s3cr3t

sf:
  generate:
     authToken:
        cron: 0 0/30 * * * *
  auth:
      url: https://cs81.salesforce.com/services/oauth2/token
  username: trial.21@cli.com.murabaha
  password: Merc$12345
  client_id: 3MVG9od6vNol.eBjAcQljw9ExDY6doeZRqtdzsk7jBOt.t1tzAWqyWZNb_bDwdGHq0FmDznw4143tBx.NwW9n
  client_secret: 8814684124517804023
  client:
      auth:
        url: https://cs81.salesforce.com/services/apexrest/mcLogin/v1/
